// @ts-nocheck
import { createClient } from '@/lib/supabase/server'
import { redirect, notFound } from 'next/navigation'
import { formatDateTime, formatDate } from '@/lib/utils/format'
import { ReportActions } from '@/components/reports/ReportActions'

interface ReportDetailPageProps {
  params: Promise<{
    id: string
  }>
}

export default async function ReportDetailPage({ params }: ReportDetailPageProps) {
  const supabase = await createClient()
  
  const { data: { session } } = await supabase.auth.getSession()
  if (!session) {
    redirect('/login')
  }

  const { id } = await params

  // Fetch the report
  const { data: report, error } = await supabase
    .from('verification_reports')
    .select(`
      *,
      criminal_records(full_name, record_id),
      profiles(full_name, employee_id, department, rank)
    `)
    .eq('id', id)
    .single()

  if (error || !report) {
    notFound()
  }

  // Parse report data
  const reportData = report.report_data as any
  const subject = reportData.subject
  const convictions = reportData.convictions || []
  const statistics = reportData.statistics || {}
  const generatedBy = reportData.generated_by || {}

  // Check if report is expired
  const isExpired = report.expires_at && new Date(report.expires_at) < new Date()

  return (
    <div className="space-y-6">
      {/* Page Header */}
      <div className="flex justify-between items-start">
        <div>
          <h1 className="text-3xl font-bold text-gray-900">{report.report_id}</h1>
          <p className="text-gray-600 mt-1">
            Verification Report Details
          </p>
        </div>
        <ReportActions reportId={report.id} reportHash={report.report_hash} />
      </div>

      {/* Status Banner */}
      {isExpired && (
        <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4">
          <div className="flex items-start gap-3">
            <svg
              className="w-5 h-5 text-yellow-600 mt-0.5 flex-shrink-0"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"
              />
            </svg>
            <div className="flex-1">
              <h3 className="text-sm font-medium text-yellow-900">Report Expired</h3>
              <p className="text-sm text-yellow-700 mt-1">
                This report expired on {formatDateTime(report.expires_at)}. The information may be outdated.
              </p>
            </div>
          </div>
        </div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Main Content */}
        <div className="lg:col-span-2 space-y-6">
          {/* Report Information */}
          <div className="bg-white rounded-lg shadow">
            <div className="px-6 py-4 border-b border-gray-200">
              <h2 className="text-lg font-semibold text-gray-900">Report Information</h2>
            </div>
            <div className="px-6 py-4 space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="text-sm font-medium text-gray-500">Report ID</label>
                  <p className="text-sm text-gray-900 font-mono">{report.report_id}</p>
                </div>
                <div>
                  <label className="text-sm font-medium text-gray-500">Report Type</label>
                  <p className="text-sm text-gray-900 capitalize">
                    {report.report_type.replace(/_/g, ' ')}
                  </p>
                </div>
                <div>
                  <label className="text-sm font-medium text-gray-500">Generated At</label>
                  <p className="text-sm text-gray-900">{formatDateTime(report.generated_at)}</p>
                </div>
                <div>
                  <label className="text-sm font-medium text-gray-500">Generated By</label>
                  <p className="text-sm text-gray-900">{report.profiles?.full_name || 'Unknown'}</p>
                  <p className="text-xs text-gray-500">{generatedBy.employee_id || 'N/A'}</p>
                </div>
                {report.expires_at && (
                  <div>
                    <label className="text-sm font-medium text-gray-500">Expires At</label>
                    <p className={`text-sm ${isExpired ? 'text-red-600 font-medium' : 'text-gray-900'}`}>
                      {formatDateTime(report.expires_at)}
                    </p>
                  </div>
                )}
                <div>
                  <label className="text-sm font-medium text-gray-500">Status</label>
                  <div className="mt-1">
                    <span
                      className={`inline-flex px-2 py-1 text-xs font-medium rounded-full ${
                        isExpired
                          ? 'bg-yellow-100 text-yellow-800'
                          : report.is_valid
                          ? 'bg-green-100 text-green-800'
                          : 'bg-red-100 text-red-800'
                      }`}
                    >
                      {isExpired ? 'Expired' : report.is_valid ? 'Valid' : 'Invalid'}
                    </span>
                  </div>
                </div>
              </div>

              {report.purpose && (
                <div>
                  <label className="text-sm font-medium text-gray-500">Purpose</label>
                  <p className="text-sm text-gray-900 mt-1">{report.purpose}</p>
                </div>
              )}

              {report.recipient && (
                <div>
                  <label className="text-sm font-medium text-gray-500">Recipient</label>
                  <p className="text-sm text-gray-900 mt-1">{report.recipient}</p>
                </div>
              )}
            </div>
          </div>

          {/* Subject Information */}
          <div className="bg-white rounded-lg shadow">
            <div className="px-6 py-4 border-b border-gray-200">
              <h2 className="text-lg font-semibold text-gray-900">Subject Information</h2>
            </div>
            <div className="px-6 py-4">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="text-sm font-medium text-gray-500">Record ID</label>
                  <p className="text-sm text-gray-900 font-mono">{subject.record_id}</p>
                </div>
                <div>
                  <label className="text-sm font-medium text-gray-500">National ID</label>
                  <p className="text-sm text-gray-900 font-mono">{subject.national_id_number}</p>
                </div>
                <div>
                  <label className="text-sm font-medium text-gray-500">Full Name</label>
                  <p className="text-sm text-gray-900">{subject.full_name}</p>
                </div>
                <div>
                  <label className="text-sm font-medium text-gray-500">Date of Birth</label>
                  <p className="text-sm text-gray-900">{formatDate(subject.date_of_birth)}</p>
                </div>
                <div>
                  <label className="text-sm font-medium text-gray-500">Gender</label>
                  <p className="text-sm text-gray-900 capitalize">{subject.gender}</p>
                </div>
                <div>
                  <label className="text-sm font-medium text-gray-500">Nationality</label>
                  <p className="text-sm text-gray-900">{subject.nationality}</p>
                </div>
                <div>
                  <label className="text-sm font-medium text-gray-500">Status</label>
                  <span
                    className={`inline-flex px-2 py-1 text-xs font-medium rounded-full ${
                      subject.status === 'active'
                        ? 'bg-green-100 text-green-800'
                        : subject.status === 'closed'
                        ? 'bg-gray-100 text-gray-800'
                        : 'bg-yellow-100 text-yellow-800'
                    }`}
                  >
                    {subject.status}
                  </span>
                </div>
                <div>
                  <label className="text-sm font-medium text-gray-500">Risk Level</label>
                  <p className="text-sm text-gray-900">{subject.risk_level}/5</p>
                </div>
              </div>

              {subject.address && (
                <div className="mt-4">
                  <label className="text-sm font-medium text-gray-500">Address</label>
                  <p className="text-sm text-gray-900 mt-1">{subject.address}</p>
                </div>
              )}

              {subject.aliases && subject.aliases.length > 0 && (
                <div className="mt-4">
                  <label className="text-sm font-medium text-gray-500">Known Aliases</label>
                  <div className="flex flex-wrap gap-2 mt-1">
                    {subject.aliases.map((alias: string, index: number) => (
                      <span
                        key={index}
                        className="px-2 py-1 text-xs bg-gray-100 text-gray-700 rounded"
                      >
                        {alias}
                      </span>
                    ))}
                  </div>
                </div>
              )}
            </div>
          </div>

          {/* Convictions */}
          <div className="bg-white rounded-lg shadow">
            <div className="px-6 py-4 border-b border-gray-200">
              <h2 className="text-lg font-semibold text-gray-900">
                Convictions ({convictions.length})
              </h2>
            </div>
            {convictions.length === 0 ? (
              <div className="px-6 py-8 text-center text-gray-500">
                <p>No convictions on record</p>
              </div>
            ) : (
              <div className="divide-y divide-gray-200">
                {convictions.map((conviction: any, index: number) => (
                  <div key={conviction.id || index} className="px-6 py-4">
                    <div className="flex justify-between items-start mb-3">
                      <div>
                        <h3 className="text-sm font-medium text-gray-900">
                          {conviction.case_number}
                        </h3>
                        <p className="text-xs text-gray-500 mt-1">
                          {conviction.court_name || 'Unknown Court'}
                        </p>
                      </div>
                      <span
                        className={`px-2 py-1 text-xs font-medium rounded-full ${
                          conviction.verdict === 'convicted' ||
                          conviction.verdict === 'serving_sentence' ||
                          conviction.verdict === 'sentence_completed'
                            ? 'bg-red-100 text-red-800'
                            : conviction.verdict === 'acquitted'
                            ? 'bg-green-100 text-green-800'
                            : 'bg-yellow-100 text-yellow-800'
                        }`}
                      >
                        {conviction.verdict.replace(/_/g, ' ')}
                      </span>
                    </div>
                    <div className="space-y-2 text-sm">
                      <div>
                        <span className="text-gray-500">Offense:</span>{' '}
                        <span className="text-gray-900">{conviction.offense_description}</span>
                      </div>
                      <div>
                        <span className="text-gray-500">Category:</span>{' '}
                        <span className="text-gray-900 capitalize">
                          {conviction.offense_category.replace(/_/g, ' ')}
                        </span>
                      </div>
                      {conviction.sentence_description && (
                        <div>
                          <span className="text-gray-500">Sentence:</span>{' '}
                          <span className="text-gray-900">{conviction.sentence_description}</span>
                        </div>
                      )}
                      <div className="flex gap-4 text-xs text-gray-500">
                        {conviction.charge_date && (
                          <span>Charged: {formatDate(conviction.charge_date)}</span>
                        )}
                        {conviction.conviction_date && (
                          <span>Convicted: {formatDate(conviction.conviction_date)}</span>
                        )}
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>

        {/* Sidebar */}
        <div className="space-y-6">
          {/* Statistics */}
          <div className="bg-white rounded-lg shadow p-6">
            <h3 className="text-sm font-medium text-gray-500 mb-4">Statistics</h3>
            <div className="space-y-3">
              <div className="flex justify-between items-center">
                <span className="text-sm text-gray-600">Total Convictions</span>
                <span className="text-lg font-semibold text-gray-900">
                  {statistics.total_convictions || 0}
                </span>
              </div>
              <div className="flex justify-between items-center">
                <span className="text-sm text-gray-600">Convicted</span>
                <span className="text-lg font-semibold text-red-600">
                  {statistics.convicted_count || 0}
                </span>
              </div>
              <div className="flex justify-between items-center">
                <span className="text-sm text-gray-600">Pending</span>
                <span className="text-lg font-semibold text-yellow-600">
                  {statistics.pending_count || 0}
                </span>
              </div>
              <div className="flex justify-between items-center">
                <span className="text-sm text-gray-600">Acquitted</span>
                <span className="text-lg font-semibold text-green-600">
                  {statistics.acquitted_count || 0}
                </span>
              </div>
            </div>
          </div>

          {/* Flags */}
          <div className="bg-white rounded-lg shadow p-6">
            <h3 className="text-sm font-medium text-gray-500 mb-4">Flags</h3>
            <div className="space-y-2">
              <div className="flex items-center gap-2">
                <div
                  className={`w-2 h-2 rounded-full ${
                    subject.is_repeat_offender ? 'bg-red-500' : 'bg-gray-300'
                  }`}
                />
                <span className="text-sm text-gray-700">Repeat Offender</span>
              </div>
              <div className="flex items-center gap-2">
                <div
                  className={`w-2 h-2 rounded-full ${
                    subject.risk_level >= 4 ? 'bg-red-500' : 'bg-gray-300'
                  }`}
                />
                <span className="text-sm text-gray-700">High Risk</span>
              </div>
              <div className="flex items-center gap-2">
                <div
                  className={`w-2 h-2 rounded-full ${
                    statistics.total_convictions >= 3 ? 'bg-orange-500' : 'bg-gray-300'
                  }`}
                />
                <span className="text-sm text-gray-700">Multiple Convictions</span>
              </div>
            </div>
          </div>

          {/* Security Hash */}
          <div className="bg-green-50 border border-green-200 rounded-lg p-4">
            <div className="flex items-start gap-3">
              <svg
                className="w-5 h-5 text-green-600 mt-0.5 flex-shrink-0"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z"
                />
              </svg>
              <div className="flex-1 min-w-0">
                <h3 className="text-sm font-medium text-green-900">Tamper-Evident</h3>
                <p className="text-xs text-green-700 mt-1">SHA-256 Hash</p>
                <p className="text-xs text-green-800 mt-2 font-mono break-all">
                  {report.report_hash}
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
